### ISSUE TITLE
Out of Memory Error

### ISSUE THREAD

**Issue by chris-wolff** [chris-wolff/java-pong#38]
Found this error when ran the game for about 15 minutes straight on Mac OS X. Full stack trace was: 
`[690.313s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 4k, detached.
Exception in thread "Thread-0" java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
        at java.base/java.lang.Thread.start0(Native Method)
        at java.base/java.lang.Thread.start(Thread.java:813)
        at java.desktop/com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1094)
        at java.desktop/com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1164)
        at pong.Game.playSound(Game.java:121)
        at pong.Game.checkWallBounce(Game.java:251)
        at pong.Game.run(Game.java:167)
        at java.base/java.lang.Thread.run(Thread.java:844)`

**Comment by chris-wolff** [comment]
Audio code was creating a thread for every single sound that needed to be played, and then letting the threads hang around after finishing playing. Solution was to kill threads with `Clip` method `close()` after listening for event indicating the sound is finished playing.

**Comment by chris-wolff** [comment]
However, solution is sloppy-looking. Is there an easier way to stop the threads after a clip is finished playing its audio. Something involving `join()`?

**Comment by chris-wolff** [comment]
Related to #23
